project:
  type: website


website:
  title: "R Stats"
  navbar:
    left:
      - icon: "journal-richtext"
        href: index.qmd
        text: Notes de cours
      - icon: "archive-fill"
        href: note_uqtr.qmd
        text: Pèle-mèle
    right:
      - icon: "bar-chart-line-fill"
        href: about.qmd
  sidebar:
    contents:
      - href: modules/module1.qmd
      - href: modules/module2.qmd
      - href: modules/module3.qmd
      - href: modules/module4.qmd
      - section: "Language R"
        contents:
        - href: R/table.qmd
        - href: R/inspect.qmd
        - href: R/explore.qmd
  repo-url: https://github.com/goneau/RStats
  repo-actions: [edit, source]


format:
  html:
    theme: simplex
    css: styles.css
    toc: true
    toc-depth: 5
    toc-expand: true
    lang: fr






